name: "Close stale issues and PRs"
on:
  schedule:
    - cron:  '00 05 * * *'

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: gorzelinski/stale@add-reaction-updates
        with:
          repo-token: ${{ secrets.GH_BOT_TOKEN }}
          stale-issue-label: status:stale
          close-issue-label: resolution:expired
          stale-issue-message: "There has been no activity on this issue for the last five years. We have marked it as stale and will close it in 30 days. We know it may be valid, so if you're interested in the solution, leave a comment or reaction under this issue."
          stale-pr-message: "There has been no activity on this PR for the last five years. We have marked it as stale and will close it in 30 days. We know it may be valid, so if you're interested in the contribution, leave a comment or reaction under this PR."
          close-issue-message: "We have closed the issue due to the lack of activity for the last five years. We know it may be valid, so you can reopen a similar issue."
          close-pr-message: "We have closed the PR due to the lack of activity for the last five years. We know it may be valid, so you can reopen a similar PR."
          days-before-stale: 1825
          days-before-close: 30
          exempt-issue-labels: support, domain:accessibility
          exempt-pr-labels: support, domain:accessibility
          ignore-reactions: false
          operations-per-run: 60
          ascending: true